### ISSUE TITLE
Automate staging deploys

### ISSUE THREAD

**Issue by LiveCSDev** [LiveChurchSolutions/Chums#32]
I'd really like to keep the staging environment in sync with the "master" branch.    The package.json files have the deployment scripts currently.  See if there's a way to run these automatically when master is updated.  Perhaps via GitHub actions.

**Comment by Levi-Huynh** [comment]
https://www.coletiv.com/blog/how-to-setup-continuous-integration-and-deployment-workflows-for-reactjs-using-github-actions/

We can probably use GH workflows to both build, run tests, and deploy to the staging & prod envs based on action subscriptions (push/pull etc) to master branch 
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions

**Comment by jzongker** [comment]
Thanks for your notes on this!  I think the steps in that article will work.  I'll try to get that one set up since I know the current AWS deployment process well.  It looks like this means "develop" will become the new primary branch we work from, but otherwise it shouldn't change much.

**Comment by jzongker** [comment]
This seems like it should be simple, but I could really use some help with it.  What I would like to happen is on a push to master it auto deploys to staging.  I can plug in the secret values.

There are already scripts in the package files for doing so that I think can be called on push.  Right now I'm using a batch file that does the following:

cd ChumsApi
call npm run deploy-staging
cd ..

cd ChumsApp
call npm run deploy-staging
cd ..

cd ChumsWeb
call npm run deploy-staging

I have added the secrets for "STAGING_AWS_ACCESS_KEY_ID" and "STAGING_AWS_SECRET_ACCESS_KEY" that you can reference.

**Comment by jzongker** [comment]
Fixed via multiple commits from irandom4 .
